# Generated by Django 4.2.2 on 2023-07-05 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("university", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StepCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                related_name="courses",
                related_query_name="courses",
                to="university.student",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="step_course",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses_step",
                related_query_name="courses_step",
                to="university.stepcourse",
            ),
        ),
    ]
